from fastapi import FastAPI
from fastapi.responses import RedirectResponse
from app.api.routes.chat import chat_router
from app.api.routes.memory import memory_router
from app.api.routes.resume import resume_router
import logging

logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger(__name__)

app = FastAPI()


@app.get("/")
async def redirect_root_to_docs() -> RedirectResponse:
    """Redirects the root URL to the API documentation.

    This endpoint provides a redirection to the /docs endpoint, which
    serves the interactive API documentation generated by FastAPI.

    Returns:
        RedirectResponse: A response that redirects to the /docs URL.
    """
    return RedirectResponse("/docs")


app.include_router(chat_router)
app.include_router(memory_router)
app.include_router(resume_router)
